[package]
name = "birb-monitor"
edition = "2024"
version = "0.1.0"
license = "MIT"
authors = [
    "Luca Ciucci <luca.ciucci99@gmail.com>",
]
description = "A cross-platform system monitoring GUI built with egui and sysinfo"

[dependencies]
anyhow = "1"
bollard = "0.21"
clap = { version = "4", features = ["derive"] }
eframe = { version = "0.36", features = ["persistence"] }
egui = "0.36"
egui_dock = { version = "0.21", features = ["serde"] }
egui_extras = "0.36"
egui_plot = "0.37"
egui_table = "0.10"
fastrand = "2.4.1"
human-units = "0.5.3"
itertools = "0.14.0"
lazy_static = "1.5.0"
ordered_hash_map = { version = "0.6.0", features = ["serde"] }
ron = "0.12.1"
serde = { version = "1.0.228", features = ["derive"] }
serde-hjson = "1.1.0"
serde_json = "1.0.150"
serde_yaml = "0.9.34"
sysinfo = "0.38.4"
toml = "1.1.2"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
ustr = "1.1.0"
uuid = { version = "1.23.1", features = ["v4"] }
ecow = { version = "0.3.1", features = ["serde"] }
tokio = { version = "1.53", features = ["full"] }
rfd = "0.17.2"
strum = "0.28.0"
strum_macros = "0.28.0"
clap_mangen = "0.3.3"

[dev-dependencies]
tokio = { version = "1.53", features = ["test-util"] }

# Used by cargo-deb
[package.metadata.deb]
license-file = "LICENSE"
section = "utils"
priority = "optional"
assets = [
    ["target/release/birb-monitor", "usr/bin/", "755"],
    ["birb-system-monitor.desktop", "usr/share/applications/", "644"],
    ["img/birb-system-monitor.svg", "usr/share/icons/hicolor/scalable/apps/", "644"],
    ["man/birb-monitor.1", "usr/share/man/man1/", "644"],
]

[profile.release-dev]
inherits = "dev"
opt-level = 3

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"
strip = true
